### PR TITLE
Add Compositional <: Known

### PR DESCRIPTION
**Pull request by juliohm**
Appreciate if you can review and merge. The compositional scientific type is widely studied in the field of compositional data analysis. There are various methodologies and textbooks handing this type of data, you can find more in the README of https://github.com/JuliaEarth/CoDa.jl

### CODE REVIEW

**Review by ablaom — COMMENTED** [review]
Sounds like a reasonable addition to me. Could you please update the type hierarchy in the readme? 

Comments you may like to consider:

Do you want to add a type parameter, as in `Compositional{N}` ?

Is there any concern about name conflict: *scitype* `Compositional` with *type* `CoDa.Compositional`? I expect your suggestion for the default convention (in ScientificTypes.jl) is that an object needs to be `CoDa.Compositional` to have scitype `Compositional`? When we added time scitypes we added a prefix, as in `ScientficTime`, `ScientificDate`, etc, which admittedly is pretty ugly (and as far as I know is not in actual use). Perhaps it's better to live with the name conflict??

**Comment by juliohm** [comment]
> Sounds like a reasonable addition to me. Could you please update the type hierarchy in the readme?

Will do, thank you for catching it.

> 
> Comments you may like to consider:
> 
> Do you want to add a type parameter, as in `Compositional{N}` ?

Very good idea, I will update a type parameter for the dimension of the composition.

> 
> Is there any concern about name conflict: _scitype_ `Compositional` with _type_ `CoDa.Compositional`? I expect your suggestion for the default convention (in ScientificTypes.jl) is that an object needs to be `CoDa.Compositional` to have scitype `Compositional`? When we added time scitypes we added a prefix, as in `ScientficTime`, `ScientificDate`, etc, which admittedly is pretty ugly (and as far as I know is not in actual use). Perhaps it's better to live with the name conflict??

The type in CoDa.jl is Composition and the scientific type is Compositional. I was inspired by the convention Text vs. Textual.

**Comment by ablaom** [comment]
> The type in CoDa.jl is Composition and the scientific type is Compositional. I was inspired by the convention Text vs. Textual.

Oh, right. I didn't catch that!

**Review by ablaom — APPROVED** [review]
✔️

**Pull request merged**
